/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageslider;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author ytr
 */
public class PanelSlider extends javax.swing.JPanel {

    /**
     * Creates new form PanelSlider
     */
    PanelThumbnail[] thumbail;
    MouseAdapter thumnailClicked = new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            PanelThumbnail panel = (PanelThumbnail) e.getSource();
            panelImgDetail.setBackground(panel.getBackground());
        }
    };

    public PanelSlider() {
        initComponents();
        thumbail = new PanelThumbnail[8];
        initThumbnail();
        btnNext.setOpaque(false);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnPrev.setOpaque(false);
        btnPrev.setBorderPainted(false);
        btnPrev.setContentAreaFilled(false);
    }

    private void initThumbnail() {
        for (int i = 0; i < thumbail.length; i++) {
            PanelThumbnail panel = new PanelThumbnail();
            panel.addMouseListener(thumnailClicked);
            thumbail[i] = panel;
            panelThumbnailContainer.add(panel);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImgDetail = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        panelThumbnailContainer = new javax.swing.JPanel();

        panelImgDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left-arrow.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/right-arrow.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImgDetailLayout = new javax.swing.GroupLayout(panelImgDetail);
        panelImgDetail.setLayout(panelImgDetailLayout);
        panelImgDetailLayout.setHorizontalGroup(
            panelImgDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgDetailLayout.createSequentialGroup()
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                .addComponent(btnNext))
        );
        panelImgDetailLayout.setVerticalGroup(
            panelImgDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgDetailLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(panelImgDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext))
                .addGap(130, 130, 130))
        );

        panelThumbnailContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImgDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelThumbnailContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImgDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelThumbnailContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        panelThumbnailContainer.remove(0);
        PanelThumbnail panel = new PanelThumbnail();
        panel.addMouseListener(thumnailClicked);
        panelThumbnailContainer.add(panel);
        panelThumbnailContainer.revalidate();
        panelThumbnailContainer.repaint();

    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        panelThumbnailContainer.remove(thumbail.length - 1);
        PanelThumbnail panel = new PanelThumbnail();
        panel.addMouseListener(thumnailClicked);
        panelThumbnailContainer.add(panel, 0);
        panelThumbnailContainer.revalidate();
        panelThumbnailContainer.repaint();
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JPanel panelImgDetail;
    private javax.swing.JPanel panelThumbnailContainer;
    // End of variables declaration//GEN-END:variables
}
